"""empty message

Revision ID: 4d2e02102198
Revises: 639c1b3c0f20
Create Date: 2024-05-28 20:08:55.514032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d2e02102198'
down_revision = '639c1b3c0f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('APP_USER', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('APP_USER', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
