"""empty message

Revision ID: 639c1b3c0f20
Revises: f5b99063b690
Create Date: 2024-05-11 14:48:43.197356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '639c1b3c0f20'
down_revision = 'f5b99063b690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('APP_SYMPTOMS', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('APP_SYMPTOMS', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
