"""empty message

Revision ID: 6bec87c65c98
Revises: c2f4d7688651
Create Date: 2024-05-11 14:02:45.485122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bec87c65c98'
down_revision = 'c2f4d7688651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('APP_PATIENT_TREATMENT',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('cancer_form_id', sa.String(length=50), nullable=False),
    sa.Column('treatment_id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('APP_FORM_CANCER_PATIENT', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('APP_FORM_CANCER_PATIENT', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('APP_PATIENT_TREATMENT')
    # ### end Alembic commands ###
