"""empty message

Revision ID: 8a48cdc130f5
Revises: 6bec87c65c98
Create Date: 2024-05-11 14:18:32.706095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a48cdc130f5'
down_revision = '6bec87c65c98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('APP_TREATMENTS',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('treatment', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('APP_PATIENT_TREATMENT', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('APP_PATIENT_TREATMENT', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('APP_TREATMENTS')
    # ### end Alembic commands ###
