"""empty message

Revision ID: a1f1005d7a08
Revises: 8a48cdc130f5
Create Date: 2024-05-11 14:33:50.069353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1f1005d7a08'
down_revision = '8a48cdc130f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('APP_PATIENT_SYMPTOMS',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('cancer_form_id', sa.String(length=50), nullable=False),
    sa.Column('symptoms_id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('APP_TREATMENTS', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('APP_TREATMENTS', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('APP_PATIENT_SYMPTOMS')
    # ### end Alembic commands ###
