"""empty message

Revision ID: c2f4d7688651
Revises: 9b60fde53474
Create Date: 2024-05-08 19:33:25.460050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2f4d7688651'
down_revision = '9b60fde53474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('APP_FORM_CANCER_PATIENT',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancer_type_region', sa.String(length=50), nullable=False),
    sa.Column('regular_health_check', sa.String(length=100), nullable=True),
    sa.Column('cancer_treatment', sa.String(length=100), nullable=True),
    sa.Column('treatment_complication', sa.String(length=100), nullable=True),
    sa.Column('life_after_treatment', sa.String(length=100), nullable=True),
    sa.Column('side_effect_care', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('APP_FORM_CANCER_PATIENT')
    # ### end Alembic commands ###
