"""empty message

Revision ID: f5b99063b690
Revises: a1f1005d7a08
Create Date: 2024-05-11 14:43:58.682654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5b99063b690'
down_revision = 'a1f1005d7a08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('APP_SYMPTOMS',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('symptoms', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('APP_PATIENT_SYMPTOMS', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('APP_PATIENT_SYMPTOMS', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('APP_SYMPTOMS')
    # ### end Alembic commands ###
